export const DATA_LIST = [
  {
    id: 1,
    title: 'Project Iceman Website',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: true,
    condition: 'new',
    category: 'car',
  },
  {
    id: 2,
    title: 'Kolapo Oladapo',
    image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
    date: '03.06.2020',
    rules: true,
    condition: 'old',
    category: 'home',
  },
  {
    id: 3,
    title: 'pixel bakery design studio',
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    date: '17.06.2021',
    rules: true,
    condition: 'new',
    category: 'home',
  },
  {
    id: 4,
    title: 'Paul D. Stewart Ltd.',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    date: '17.11.2019',
    rules: true,
    condition: 'new',
    category: 'car',
  },
  {
    id: 5,
    title: 'TribeVibe',
    image: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
    date: '28.12.2019',
    rules: true,
    condition: 'old',
    category: 'car',
  },
  {
    id: 6,
    title: 'AXEPT',
    image: 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg',
    date: '21.05.2022',
    rules: true,
    condition: 'new',
    category: 'home',
  },
  {
    id: 7,
    title: 'Halborn',
    image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    date: '24.01.2020',
    rules: true,
    condition: 'new',
    category: 'car',
  },
  {
    id: 8,
    title: 'Comedy Carnival',
    image: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg',
    date: '27.05.2022',
    rules: true,
    condition: 'new',
    category: 'car',
  },
  {
    id: 9,
    title: 'Supercool',
    image: 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg',
    date: '18.04.2019',
    rules: true,
    condition: 'new',
    category: 'car',
  },
  {
    id: 10,
    title: 'Hivecell',
    image: 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg',
    date: '21.10.2021',
    rules: true,
    condition: 'old',
    category: 'car',
  },
];
