export const DATA_LIST = [
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
  {
    id: Math.trunc(Math.random() * 1e8),
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    date: '12.12.2000',
    rules: false,
    condition: 'new',
    category: 'car',
  },
];
